# Please see the documentation for all possible configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    target-branch: "cosine"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "cosine"
    schedule:
      interval: "weekly"
