base_path: locales
files:
  - source: en-US/sine-preferences.ftl
    translation: sine-preferences.ftl
  - source: en-US/sine-toasts.ftl
    translation: sine-toasts.ftl
  - source: en-US/sine-cmdpalette.ftl
    translation: sine-cmdpalette.ftl
