name: Deploy latest assets

on:
  workflow_dispatch:
    inputs:
      sine_version:
        type: string
        description: "Sine version to release (include patch number, no 'v')"
        required: true
      version_type:
        type: number
        description: "Version type (0: normal, 1: abnormal, 2: bootloader, see docs/updates.md)"
        required: true

permissions:
  contents: write
  actions: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt install jq

      - name: Create artifacts directory
        run: mkdir artifacts/

      - name: Ensure inputs are in proper format
        run: |
          # Ensure that Sine version format is proper
          sine_version="${{ inputs.sine_version }}"
          if [[ "$sine_version" =~ ^[0-9]+(\.[0-9]*(\.[0-9]+\.?)?)?\.?$ ]]; then
            exit 1
          fi
          if [[ "$sine_version" == v* ]]; then
            exit 1
          fi
          if [[ "$sine_version" == *c ]]; then
            exit 1
          fi

          # Ensure that version type is proper
          version_type="${{ inputs.version_type }}"
          if [[ "$version_type" != "0" && "$version_type" != "1" && "$version_type" != "2" ]]; then
            exit 1
          fi

      - name: Determine branch suffix
        id: extract_branch
        run: |
          if [[ "$GITHUB_HEAD_REF" == "cosine" ]]; then
            suffix="c"
          fi
          echo "suffix=${suffix:-}" >> $GITHUB_OUTPUT

      - name: Format inputs for build workflow
        id: format_inputs
        run: |
          # Remove patch number and potentially the small release number
          sine_version="${{ inputs.sine_version }}"
          sine_version="${sine_version%.*}"
          if [[ "$sine_version" == *.0 ]]; then
            sine_version="${ver%.0}"
          fi
          sine_version="${sine_version}${{ steps.extract_branch.outputs.suffix }}"
          echo "sine_version=$sine_version" >> $GITHUB_OUTPUT

          # Retrieve boot version from engine.json
          boot_version="$(jq -r '.bootloader' engine.json)"
          echo "boot_version=$boot_version" >> $GITHUB_OUTPUT

      - name: Trigger build workflow
        id: build_job
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          inputs: '{ "sine_version": "${{ steps.format_inputs.outputs.sine_version }}", "boot_version": "${{ steps.format_inputs.outputs.boot_version }}" }'
          wait-for-completion: true

      - name: Download artifacts
        run: |
          run_id=${{ steps.build_job.outputs.runId }}
          gh run download $run_id -D artifacts/
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Organize artifacts
        run: |
          for folder in artifacts/*/; do
            [ -d "$folder" ] || continue
            file=$(find "$folder" -maxdepth 1 -type f)
            filename=$(basename "$file")
            foldername=$(basename "$folder")

            if [ "$filename" = "$foldername" ]; then
              extension="${filename##*.}"
              tempname="${foldername}_file.$extension"
              mv "$file" "artifacts/$tempname"
              rmdir "$folder"
              mv "artifacts/$tempname" "artifacts/$filename"
            else
              mv "$file" artifacts/
              rmdir "$folder"
            fi
          done

      - name: Download updater scripts
        run: |
          curl -L -o artifacts/updater.bat https://raw.githubusercontent.com/sineorg/installer/main/updater.bat
          curl -L -o artifacts/updater.sh https://raw.githubusercontent.com/sineorg/installer/main/updater.sh

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Update engine metadata
        run: |
          jq '.updates[0] |= . + {
            "version": "'"${{ inputs.sine_version }}${{ steps.extract_branch.outputs.suffix }}"'",
            "type": '"${{ inputs.version_type }}"'
          }' engine.json > engine.json.tmp
          mv engine.json.tmp engine.json

      - name: Generate packages
        run: |
          pip install -r scripts/requirements.txt
          python scripts/package.py
          mv engine.zip artifacts/engine.zip

      - name: Get latest release
        id: latest_release
        run: |
          latest=$(gh release list --limit 1 --json tagName,isPrerelease,publishedAt --jq '.[0].tagName')
          echo "Latest release tag: $latest"
          echo "release_tag=$latest" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts to latest release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.latest_release.outputs.release_tag }}
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger auto-updating
        run: |
          sine_version="${{ steps.format_inputs.outputs.sine_version }}"
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git add engine.json
          git commit -m "Trigger auto-updating for $sine_version"
          git push -u main
